schema: 'lambda/graphql/typeDefs/**/!(index).ts'
documents: 'src/documents/**/*.graphql'
extensions:
  codegen:
    overwrite: true
    config:
      constEnums: true
      immutableTypes: true
      avoidOptionals: true
      nonOptionalTypename: true
    generates:
      # for graphql server resolvers
      codegen/resolver-types.ts:
        config:
          useIndexSignature: true
        plugins:
          - typescript
          - typescript-resolvers:
              avoidOptionals: false
      # for react app querys
      codegen/document-types.ts:
        plugins:
          - typescript
          - typescript-operations
          - typescript-react-apollo
