[build]
command = "yarn run install:all && yarn run build"
publish = "client/dist"
functions = "api/functions"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = false

[dev]
publish = "dist"
