import 'reflect-metadata';
import { buildSchemaSync } from 'type-graphql';
import { QueryResolver, ProjectResolver } from '../api/src/resolver';
import path from 'path';

buildSchemaSync({
  resolvers: [QueryResolver, ProjectResolver],
  emitSchemaFile: path.resolve(__dirname, '..', 'gql', 'apiSchema.gql'),
});

console.log('api graphql schema has generated by type-graphql');
