root: true
env:
  node: true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2020
  sourceType: module
  project: tsconfig.json
plugins:
  - '@typescript-eslint'
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - prettier
rules:
  '@typescript-eslint/no-unused-vars':
    - warn
    - argsIgnorePattern: ^_
      ignoreRestSiblings: true
